name: demix
channels:
    - pytorch
dependencies:
    - pytorch
    - pip
    - pip:
        - pandas
        - humanize
        - transformers
        - scikit-learn
        - fairseq
        - git+https://github.com/fadel/pytorch_ema
